version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes: 
    - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

