import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Home from '@/icons/Home'
import UserGroup from '@/icons/UserGroup'

const inter = Inter({ subsets: ['latin'] })

const MENU_WIDTH = 48

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const SidebarContent: React.FC = () => (
  <aside className={`bg-gray-800 text-primary w-${MENU_WIDTH}`}>
    <ul className={`menu p-3 bg-base-200 h-full w-${MENU_WIDTH}`}>
      <li className="menu-title">
        <span>Menu</span>
      </li>
      <li>
        <a href="/">
          <Home height={24} width={24} />
          Home
        </a>
      </li>
      <li>
        <a href="/users">
          <UserGroup height={24} width={24} />
          Users
        </a>
      </li>
    </ul>
  </aside>
)

const Navbar: React.FC = () => (
  <nav className="navbar bg-primary text-primary-content">
    <div className="flex-1">
      <a className="btn btn-ghost normal-case text-xl" href="/">Next.js Boilerplate</a>
    </div>
    <div className="flex-none">
      <div className="dropdown dropdown-end">
        <label tabIndex={0} className="btn btn-ghost btn-circle avatar">
          <div className="w-10 rounded-full">
            <Image src="/avatar.svg" alt="avatar.svg" fill />
          </div>
        </label>
        <ul tabIndex={0} className="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-200 rounded-box w-52 text-primary">
          <li><a href="/profile">Profile</a></li>
          <li><a>Logout</a></li>
        </ul>
      </div>
    </div>
  </nav>
)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex h-screen">
          <SidebarContent />
          <div className="flex-grow">
            <div className="flex min-h-screen flex-col items-center justify-between p-24">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
